apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-svc
spec:
  selector:
    matchLabels:
      app: admin-svc
  template:
    metadata:
      labels:
        app: admin-svc
    spec:
      containers:
      - name: admin-svc
        image: arigatory/moviepoisk-admin
        imagePullPolicy: Always
        env:
          - name: DB_NAME
            value: movies_database
          - name: DB_USER
            value: doadmin
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-secret
                key: postgresPw
          - name: DB_HOST
            value: postgresql-do-user-16123669-0.c.db.ondigitalocean.com
          - name: SECRET_KEY
            value: 'django-very-secure-&k7sh3ku#(m_7@0=!57d19@e94=d0j1cpba=@n=f--is9p0#r5'
          - name: DEBUG
            value: 'True'
          - name: ALLOWED_HOSTS
            value: '127.0.0.1 0.0.0.0 moviepoisk.ru'
          - name: DB_PORT
            value: '25060'
---
apiVersion: v1
kind: Service
metadata:
  name: admin-clusterip
spec:
  type: ClusterIP
  selector:
    app: admin-svc
  ports:
  - port: 80
    targetPort: 8000

        
