apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  labels:
    name: ingress-svc
spec:
  rules:
  - host: admin.moviepoisk.ru
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: admin-clusterip
            port: 
              number: 80
